# Numpy

## Revisiting Python List

In [1]:
#Creating different lists in Python
item_list = ['Bread', 'Milk', 'Eggs', 'Butter', 'Cocoa']
student_marks = [78, 47, 96, 55, 34]
hetero_list =  [ 1,2,3.0, 'text', True, 3+2j ]
print('Item list: ', item_list)
print('Student marks: ', student_marks)
print('Heterogenous list: ', hetero_list)

Item list:  ['Bread', 'Milk', 'Eggs', 'Butter', 'Cocoa']
Student marks:  [78, 47, 96, 55, 34]
Heterogenous list:  [1, 2, 3.0, 'text', True, (3+2j)]


In [2]:
#Adding 5 to all the student marks
student_marks = [78, 47, 96, 55, 34]
for i in range(len(student_marks)):
    student_marks[i]+=5
print(student_marks)

[83, 52, 101, 60, 39]


## Limitations of Python list- Slow performance

In [3]:
%%time
#Used to calculate total operation time
list1 = list(range(1,1000000))

list2 = list(range(2,1000001))

list3 = []

for i in range(len(list1)):
    list3.append(list1[i]+list2[i])
    

Wall time: 872 ms


In [4]:
%%time
#Used to calculate total operation time

#Importing Numpy
import numpy as np
#Creating a numpy array of 1 million numbers
a = np.arange(1,1000000)
b = np.arange(2,1000001)
c = a+b


Wall time: 423 ms


In [2]:
#Getting started with Numpy- Importing Numpy
import numpy as np

## Array object creation

In [6]:
import numpy as np
student_marks_arr = np.array([78, 92, 36, 64, 89])
student_marks_arr

array([78, 92, 36, 64, 89])

In [7]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
horsepower_arr

array([130, 165, 150, 150, 140])

In [8]:
#creating a list of lists of mpg, horsepower and acceleration values
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
#creating a numpy array from attributes list
car_attributes_arr = np.array(car_attributes)
car_attributes_arr

array([[ 18,  15,  18,  16,  17],
       [130, 165, 150, 150, 140],
       [307, 350, 318, 304, 302]])

## Shape of array

In [9]:
car_attributes_arr.shape

(3, 5)

## Dtype of array

In [10]:
car_attributes_arr.dtype

dtype('int32')

## Converting Dtype

In [11]:
#converting dtype
#creating a list of lists of 5 mpg, horsepower and acceleration values
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
#creating a numpy array from attributes list
car_attributes_arr = np.array(car_attributes, dtype = 'float')
print(car_attributes_arr)
print(car_attributes_arr.dtype)

[[ 18.  15.  18.  16.  17.]
 [130. 165. 150. 150. 140.]
 [307. 350. 318. 304. 302.]]
float64


## Operations on arrays

### Accessing elements

In [13]:
#creating an array of cars
cars = np.array(['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
cars[1]

'buick skylark 320'

In [16]:
#Creating a 2D array consisting car names and horsepower
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
car_hp_arr

array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140']], dtype='<U25')

In [7]:
#Creating a 2D array consisting car names and horsepower
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
#Accessing car names
car_hp_arr[1]

array(['130', '165', '150', '150', '140'], dtype='<U25')

In [46]:
#Creating a 2D array consisting car names and horsepower
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
#Accessing horsepower
car_hp_arr[1]

array(['130', '165', '150', '150', '140'], dtype='<U25')

In [5]:
import numpy as np
#Creating a 2D array consisting car names and horsepower
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
#Accessing second car
car_hp_arr[0:3]

array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140']], dtype='<U25')

In [8]:
#Creating a 2D array consisting car names and horsepower
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])

#Accessing name and horsepower of last car
print(car_hp_arr[[0,1],[4,4]])

['ford torino' '140']


In [49]:
#Creating a 2D array consisting car names and horsepower
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
#Accessing name of last car using negative indexing
car_hp_arr[0,-1]

'ford torino'

### Slicing

In [52]:
#creating an array of cars
cars = np.array(['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
#accessing a subset of cars from the array
cars[1:4]

array(['buick skylark 320', 'plymouth satellite', 'amc rebel sst'],
      dtype='<U25')

In [24]:
#Creating a 2D array consisting car names, horsepower and acceleration
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
car_hp_acc_arr

array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140'],
       ['18', '15', '18', '16', '17']], dtype='<U25')

In [25]:
#Creating a 2D array consisting car names, horsepower and acceleration
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
#Accessing name and horsepower 
car_hp_acc_arr[0:2]

array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140']], dtype='<U25')

In [26]:
#Creating a 2D array consisting car names, horsepower and acceleration
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
#Accessing name and horsepower of last two cars 
car_hp_acc_arr[0:2, 3:5]

array([['amc rebel sst', 'ford torino'],
       ['150', '140']], dtype='<U25')

In [59]:
#Creating a 2D array consisting car names, horsepower and acceleration
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
#Accessing name, horsepower and acceleration of first three cars
car_hp_acc_arr[0:3, 0:3]

array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite'],
       ['130', '165', '150'],
       ['18', '15', '18']], dtype='<U25')

## Mean, median, minimum, maximum

In [61]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
#mean horsepower
print("Mean horsepower = ",np.mean(horsepower_arr))

Mean horsepower =  147.0


In [86]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
#median horsepower
print("Median horsepower = ",np.median(horsepower_arr))

Median horsepower =  150.0


In [133]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
print("Minimum horsepower: ", np.min(horsepower_arr))
print("Maximum horsepower: ", np.max(horsepower_arr))

Minimum horsepower:  130
Maximum horsepower:  165


In [13]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
print("Index of Minimum horsepower: ", np.argmin(horsepower_arr))
print("Index of Maximum horsepower: ", np.argmax(horsepower_arr))

Index of Minimum horsepower:  0
Index of Maximum horsepower:  1


## Querying/Searching in an array

In [66]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
x = np.where(horsepower_arr >= 150)
print(x) # gives the indices 
# With the indices , we can find those values 
horsepower_arr[x]


(array([1, 2, 3], dtype=int64),)


array([165, 150, 150])

## Sorting an array

In [67]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
#using sort(array)
print('original array: ', horsepower_arr)
print('Sorted array: ', np.sort(horsepower_arr))
print('original array after sorting: ', horsepower_arr)


original array:  [130 165 150 150 140]
Sorted array:  [130 140 150 150 165]
original array after sorting:  [130 165 150 150 140]


In [69]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
#using sort(array)
print('original array: ', horsepower_arr)
horsepower_arr.sort()
print('original array after sorting: ', horsepower_arr)


original array:  [130 165 150 150 140]
original array after sorting:  [130 140 150 150 165]


## Filtering an array

In [76]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
#creating filter array
filter_arr = horsepower_arr > 135

newarr = horsepower_arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True  True  True  True]
[165 150 150 140]


## Vectorized operations

In [6]:
import numpy as np
student_marks_arr = np.array([78, 92, 36, 64, 89])
student_marks_arr

array([78, 92, 36, 64, 89])

In [7]:
np.sum(student_marks_arr)

359

In [9]:
additional_marks = [2, 2, 5, 10, 1]
student_marks_arr += additional_marks
student_marks_arr

array([80, 94, 41, 74, 90])

In [10]:
student_marks_arr = np.array([78, 92, 36, 64, 89])
student_marks_arr = np.add(student_marks_arr, additional_marks)
student_marks_arr

array([80, 94, 41, 74, 90])

## Broadcasting


In [12]:
# Array 1
array1=np.array([5, 10, 15])
# Array 2
array2=np.array([5])
array3= array1 * array2 
array3

array([25, 50, 75])

In [113]:
#Students marks in 4 subjects
students_marks = np.array([[67, 45],[90, 92],[66, 72],[32, 40]])
students_marks

array([[67, 45],
       [90, 92],
       [66, 72],
       [32, 40]])

In [112]:
#Broadcasting
students_marks += 5
students_marks

array([[72, 50],
       [95, 97],
       [71, 77],
       [37, 45]])

In [114]:
#Broadcasting
students_marks += [5,10]
students_marks

array([[ 72,  55],
       [ 95, 102],
       [ 71,  82],
       [ 37,  50]])

## Arange
Returns evenly spaced values between the given intervals in accordance with the step value, excluding the end limit. The step value is 1 by default.

In [157]:
#start and end limit
np.arange(0,10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [158]:
#step value = 2
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

#### Linspace
Returns the given number of evenly spaced values between the given intervals. The number of values between a given interval will be 50.

In [159]:
arr = np.linspace(0,10)
print(arr)
print('Length of arr: ',len(arr))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
Length of arr:  50


In [160]:
#Number of values = 3
np.linspace(0,10,3)

array([ 0.,  5., 10.])

#### zeros
Returns an array of given shape, filled with zeros

In [161]:
#1D
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [162]:
#2D
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

#### ones
Returns an array of given shape, filled with ones.

In [163]:
#1D
np.ones(3)

array([1., 1., 1.])

In [164]:
#2D
np.ones([2,1])

array([[1.],
       [1.]])

#### full
Returns an array of given shape, filled with given value, irrespective of datatype.


In [166]:
#number=5, value=8
np.full(5,8)

array([8, 8, 8, 8, 8])

In [167]:
#shape=[3,3], value=numpy
np.full([3,3],'numpy')

array([['numpy', 'numpy', 'numpy'],
       ['numpy', 'numpy', 'numpy'],
       ['numpy', 'numpy', 'numpy']], dtype='<U5')

#### eye
Returns an identity matrix for the given shape.

In [168]:
#3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### diag
Returns a diagonal matrix with the given list of values.

In [170]:
#list of 3 values
np.diag([1,3,5])

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

#### Random
NumPy has numerous ways to create random number arrays. By just passing the value of required length to the random.rand function, we can create random numbers for the required length, from an uniform distribution.


In [5]:
#generating 5 random numbers from a uniform distribution
np.random.rand(5)

array([0.54411574, 0.78618183, 0.78445232, 0.39903718, 0.640299  ])

Similarly if you want to generate random numbers from a Normal distribution, use random.randn function. <br>
Random numbers of type 'integer' can also be generated using random.randint function.

In [6]:
np.random.randint(1,10,size=5)

array([9, 5, 1, 6, 4])

In [8]:
#random integer values high=100, shape = (3,5)
x = np.random.randint(100, size=(3, 5))
print(x)
print(type(x))


[[54 20 49 42 95]
 [80  0 45  1 59]
 [38 57 74 55 37]]
<class 'numpy.ndarray'>


Here, we have created 5 random numbers between 1 and 10. Once if all the possible combinations of random numbers did not suffice, the random.randint function will return redundant values.

In [9]:
#returns a single random value from the array
x = np.random.choice([9, 3, 7, 5])
print(x)


3


In [11]:
#returns 3*5 random values from the array
x = np.random.choice([9, 3, 7, 5], size=(3, 5))   # sampling to create an nd-array 
print(x)
print(type(x))


[[3 5 5 5 5]
 [7 3 7 9 7]
 [7 3 3 5 9]]
<class 'numpy.ndarray'>
